apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-creds
data:
  credentials: |
    [default]
    aws_access_key_id = AKIAXWEIKGZPGKOF6GUD
    aws_secret_access_key = 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